// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihz24BLGxDjkarNPg7Brq-ZtzeABsLKU',
    appId: '1:719190988428:web:82432fe2463744087d8da9',
    messagingSenderId: '719190988428',
    projectId: 'todolist-7ce51',
    authDomain: 'todolist-7ce51.firebaseapp.com',
    storageBucket: 'todolist-7ce51.firebasestorage.app',
    measurementId: 'G-36DGWQVL83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-WumVwUWtbk6NxFpbop1dz6ah4QfzpDw',
    appId: '1:719190988428:android:6943752181a00c7d7d8da9',
    messagingSenderId: '719190988428',
    projectId: 'todolist-7ce51',
    storageBucket: 'todolist-7ce51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3NSkCf00b0u4YOnCc2DNK-gz6OdEcm50',
    appId: '1:719190988428:ios:9c9ac860f69d623e7d8da9',
    messagingSenderId: '719190988428',
    projectId: 'todolist-7ce51',
    storageBucket: 'todolist-7ce51.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3NSkCf00b0u4YOnCc2DNK-gz6OdEcm50',
    appId: '1:719190988428:ios:9c9ac860f69d623e7d8da9',
    messagingSenderId: '719190988428',
    projectId: 'todolist-7ce51',
    storageBucket: 'todolist-7ce51.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBihz24BLGxDjkarNPg7Brq-ZtzeABsLKU',
    appId: '1:719190988428:web:7b02f40da930ced27d8da9',
    messagingSenderId: '719190988428',
    projectId: 'todolist-7ce51',
    authDomain: 'todolist-7ce51.firebaseapp.com',
    storageBucket: 'todolist-7ce51.firebasestorage.app',
    measurementId: 'G-XS7SQGE68C',
  );
}
